### ISSUE TITLE
0.2.0 - no such file to load -- akephalos

### ISSUE THREAD

**Issue by joeybeninghove** [bernerdschaefer/akephalos#1]
Ruby 1.8.7 p299

Steps:
1. rvm gemset create test
2. rvm gemset use test
3. gem install akephalos
4. irb
5. require 'akephalos'

Error: LoadError: no such file to load -- akephalos

**Comment by bernerdschaefer** [comment]
Okay. This should be fixed in 0.2.2 -- there was a bug in the gemspec which mucked up the require paths. Thanks!
