### ISSUE TITLE
Syntax error, unrecognized expression: ([data-remote])

### ISSUE THREAD

**Issue by joeybeninghove** [bernerdschaefer/akephalos#2]
REE 1.8.7
Rails 3 edge

One of my custom cucumber steps is failing with this:

<pre>
com.gargoylesoftware.htmlunit.ScriptException: Syntax error, unrecognized expression: ([data-remote]) (http://localhost:9887/javascripts/jquery-1.4.2.min.js?1278105420#75) (NativeException)
      (drbunix:///tmp/akephalos.20972.sock) -e:1
      ./features/step_definitions/applicant_steps.rb:20:in `/^I click the link from my email invitation to start filling out my assessment$/'
</pre>

Here is the capybara usage:

<pre><code>
visit(edit_user_password_path(:reset_password_token => @reset_password_token))
</code></pre>

Any reason the data-remote attribute would throw htmlunit for a loop?

**Comment by joeybeninghove** [comment]
Happens because of htmlunit's lack of official support for jQuery 1.4.2... 

Per Bernerd's instructions:
bin/akephalos --use-htmlunit-snapshot, and then running the tests

That takes care of this error by using the latest htmlunit snapshot.

**Comment by bernerdschaefer** [comment]
Closing out. Akephalos is now on HtmlUnit 2.8.
