### ISSUE TITLE
Needs register_driver call

### ISSUE THREAD

**Issue by wincent** [bernerdschaefer/akephalos#23]
I gather that recent changes in Capybara require that Akephalos register itself like this:

```
Capybara.register_driver :akephalos do |app|
  Capybara::Driver::Akephalos.new(app)
end
```

Without this, things blow up with:

```
 no driver called :akephalos was found, available drivers:
 :rack_test, :selenium, :culerity, :celerity
```

I guess this commit is the one that introduced the breakage:

http://github.com/jnicklas/capybara/commit/7fc12fd78ea3bf642236cf62315ec73f4272a567

There have probably been other changes in Capybara too, as even with registering the driver I am seeing this kind of failure:

```
 undefined local variable or method `node' for
#<Capybara::Driver::Akephalos::Node:0x105754508>
```

But I guess that's a separate issue... If I figure out what is going on I'll open a ticket for that one.

Cheers,
Wincent

**Comment by bernerdschaefer** [comment]
You should no longer see this on the 'capybara-head' branch. I'll most likely still be publishing versions of akephalos before capybara is released again, so I'm isolating these changes in that branch.

Thanks for the heads up. Closing out.
