### ISSUE TITLE
undefined local variable or method "node"

### ISSUE THREAD

**Issue by wincent** [bernerdschaefer/akephalos#24]
As I mentioned in issue #23, I'm seeing this kind of error in with current HEAD of Capybara and Akephalos:

```
undefined local variable or method `node' for
#<Capybara::Driver::Akephalos::Node:0x105753ce8>
```

Not yet sure, but a `git log --grep=node` suggests that one of these two commits might have something to do with the breakage:

http://github.com/jnicklas/capybara/commit/2ea3607870ebe882f79960c90be742ffac8c4295

http://github.com/jnicklas/capybara/commit/f2509fb1af835fad4f2a8fa7904cf68fc47f4d1b

Still haven't been able to pin this one down exactly though, as RSpec 2 doesn't seem to show full backtraces any more (even with the `--backtrace` switch).

Cheers,
Wincent

**Comment by bernerdschaefer** [comment]
You should no longer see this on the 'capybara-head' branch. I'll most likely still be publishing versions of akephalos before capybara is released again, so I'm isolating these changes in that branch.

Thanks for the heads up. Closing out.

**Comment by wincent** [comment]
Thanks for the fix (and on the other ticket I posted too). Tested here and confirmed working.

Cheers,
Wincent
