### ISSUE TITLE
Using akephalos to test a page with canvas

### ISSUE THREAD

**Issue by vinibaggio** [bernerdschaefer/akephalos#26]
Is there a way to use akephalos to test a webpage that contains a canvas? I'm currently getting the following error:

com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot find function translate in object [object CanvasRenderingContext2D]. (http://localhost:9887/javascripts/jquery.flot.js?1279636309#1508)
(drbunix://tmp/akephalos.58289.sock) /Users/vinibaggio/.rvm/gems/ree-1.8.7-2010.02/gems/akephalos-0.2.4/lib/akephalos/client.rb:54:in `visit
(drbunix://tmp/akephalos.58289.sock) /Users/vinibaggio/.rvm/gems/ree-1.8.7-2010.02/gems/akephalos-0.2.4/lib/akephalos/server.rb:29:in`start!'
(drbunix://tmp/akephalos.58289.sock) -e:1

Thanks!

**Comment by dennisreimann** [comment]
We're having the same problem with a HTML5 video element:

com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot find function play in object [object HTMLUnknownElement]. (http://localhost:9887/video-js/video.js?1289005154#260) (NativeException)
(druby://127.0.0.1:51696) -e:1

**Comment by bernerdschaefer** [comment]
Until HtmlUnit decides to implement the HTML5 spec, I think the best option for this sort of problems will be to stub out those calls, perhaps with Filters (http://oinopa.com/akephalos/filters.html).

I will consider the feasibility of implementing stubbed methods of HTML5 functions directly from Akephalos.

**Comment by vinibaggio** [comment]
ok, thanks!
