### ISSUE TITLE
Ruby crash: gc_sweep(): unknown data type

### ISSUE THREAD

**Issue by neomindryan** [bernerdschaefer/akephalos#30]
This appears to be a bug in Ruby not Akephalos, but I wanted to post here in case anybody else is having the problem. Upgrading to Ruby-1.8.7-p302 seems to have fixed the problem.

Here's the error message:
gems/activesupport-2.3.4/lib/active_support/callbacks.rb:180: [BUG] gc_sweep(): unknown data type 0x0(0x1057182d8)
ruby 1.8.7 (2010-04-19 patchlevel 253) [i686-darwin10.4.0], MBARI 0x6770, Ruby Enterprise Edition 2010.02

I'm using RVM with REE-1.8.7-2010.02 and Rails 2.3.4 on OSX. Capybara is version 0.3.9, and I've configured it with "Capybara.javascript_driver = :akephalos"
I've also reproduced this crash on REE-1.8.7-2010-01 and Ruby-1.8.7-p249

**Comment by bry4n** [comment]
I had the same problem with ree 1.8.7 (with patchlevel 253), but ree-head or 1.8.7 MRI is working fine.

**Comment by bernerdschaefer** [comment]
I've most often run into this issue with REE, but yeah, it's also in certain patch levels of MRI. Closing out since it's not related to akephalos.

**Comment by jrom** [comment]
I also had this issue with `ruby-1.8.7-p249` and fixed by switching to `ree-head`.
