### ISSUE TITLE
Capybara 0.4 compatibility

### ISSUE THREAD

**Issue by jnicklas** [bernerdschaefer/akephalos#31]
any chance we can get a 0.4 compatible version? Let me know if there's any way I can help!

**Comment by fidothe** [comment]
I've just run into this. I've forked and am trying to get it working - most of the problems were with needing RSpec 2 and then with the new split between Capybara::Node and Capybara::Driver::Node. I'm getting somewhere, seems to mostly be problems with scoping now. Jonas, if you could spare some time on IRC or IM to help me understand some of the underlying stuff that would probably really help.

Cheers,

Matt

**Comment by jnicklas** [comment]
fidothe: I'll be online in #ruby-lang for the next couple of hours.

**Comment by fidothe** [comment]
So, I've spent today trying to get Akephalos working with Capybara 0.4, with some success. The changes were quite serious, but essentially only within the Capybara::Driver::Akephalos and Capybara::Driver::Akephalos::Node classes. It's not quite there, but I got to within 6 failing specs of the finish... The last two commits in my fork have the work so far. The first commit (https://github.com/fidothe/akephalos/commit/6b3f368a001a80b576cd7e872607943adb14033d) is just the infrastructure changes: updated gemspec and tweaking around for RSpec 2 (Actually, I just realised I haven't updated the Rake task for RSpec -- I've been running the specs with `rspec spec`), and the second commit (https://github.com/fidothe/akephalos/commit/40674ad2cc3c1eedc8b98cbac000adaa04d27efd) has the code changes.

**Comment by bernerdschaefer** [comment]
Have you checked out the capybara-head branch? I haven't touched it in a while, but as of a few weeks ago it only failed 2 integration specs.

**Comment by fidothe** [comment]
Ah, I hadn't seen that. It's currently failing 8 specs in 0.4 (as released) and 7 specs in capybara's HEAD. My version does a tiny bit better - 6 failing specs in 0.4 and HEAD, but the differences between what we've done basically boil down to what I did in Akephalos::Node#value in lib/akephalos/node.rb. All the non-value-related failures seem to be in both my branch and yours.

**Comment by pboling** [comment]
I also need compatibility with Capybara 0.4.0.  I will be stepping into this during the next few days to see what I can work out.  Already forked fidothe.

**Comment by bernerdschaefer** [comment]
I've now merged in the various work that's been going into 0.4 compatibility. Looks like there are still 3 failing specs from the capybara suite, however.

**Comment by jnicklas** [comment]
Just checked it out. Looks like those are all related to drag and drop, which fails for Celerity too. Don't think this is much of a problem, tbh, since it hasn't worked before, and the problem was only masked by an insufficient test suite in Capybara 0.3.X. All we need now is a gem release! ;)

**Comment by wincent** [comment]
Really glad to see the progress on this!

Akephalos is currently the only Git-based gem in my `Gemfile`. Looking forward to being able to switch it back to a gem release in `vendor/cache` so that I can decouple my deployments from GitHub.

Keep up the good work!

**Comment by bernerdschaefer** [comment]
Okay! I investigated the failing specs, and have marked them pending as appropriate. Explanation here: https://github.com/bernerdschaefer/akephalos/commit/44073fcfece030424418981038c6e3085cc2c5ba

Hoping to get a release out shortly!

**Comment by bernerdschaefer** [comment]
And done: https://rubygems.org/gems/akephalos

**Comment by wincent** [comment]
Nice one!

**Comment by fidothe** [comment]
Hurrah!

**Comment by jnicklas** [comment]
yay! awesome!

**Comment by sorentwo** [comment]
Hmm, I think I should have indicated I had this working in December with a pull request. Glad to see it is official!

**Comment by simaob** [comment]
Awesome guys =)
