### ISSUE TITLE
akephalos brokes rspec

### ISSUE THREAD

**Issue by petRUShka** [bernerdschaefer/akephalos#32]
I use Rails 3, Ruby 1.9.2 and latest akephalos gem.

Rspec was broken after I added akephalos gem to Gemfile. 

There is gist: https://gist.github.com/665507

For example, cucumber is ok.

**Comment by oriolgual** [comment]
Same happening here with the same config

**Comment by oriolgual** [comment]
My fault, add akephalos to your Gemfile with :require => false, i.e:
gem "akephalos", :require => false

And then require it when you set up the driver (like the docs say):
require 'akephalos'
Capybara.javascript_driver = :akephalos

**Comment by bernerdschaefer** [comment]
I'll see if there's a reasonable fix for this, otherwise this is a common solution for other testing tools; closing out for now.
