### ISSUE TITLE
Accented characters

### ISSUE THREAD

**Issue by vinibaggio** [bernerdschaefer/akephalos#36]
Hello, 

My application is currently in Brazilian portuguese and I have to test for accented characters, for example: "Político" (theres an acute accent in the first i). Pages are rendered with accented characters correctly. The problem happens when I use Akephalos to type in some value in a text field. The result page shows up like "Pol��tico".

I've been able to fix that by changing the bin/akephalos script in order to call jRuby with the -Ku parameter:

<pre>
    ruby_args = [
      "-Ku",
      "-I", "vendor:#{lib}:#{src}",
      "-r", "akephalos/server",
      "-e", "Akephalos::Server.start!(#{port.inspect})"
    ]
</pre>

I would happily do a patch/pull request, but I unfortunately wasn't able to write a failing test, since tests run in the same encoding context. Is there an idea how can I be able to test this?

Thanks!

**Comment by bernerdschaefer** [comment]
This has been pulled in. Thanks!
