### ISSUE TITLE
"COMSCORE" is not defined.

### ISSUE THREAD

**Issue by emilford** [bernerdschaefer/akephalos#37]
I am getting the following error when running my first set of steps.  Rails 3, capybara head, akephalos 'capybara-head' on Mac OS X.  Any ideas how to resolve this?  Thanks.

com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "COMSCORE" is not defined. (script in http://localhost:51526/login from (320, 36) to (331, 14)#322) (NativeException)

**Comment by bernerdschaefer** [comment]
I'd have to see more detail, but my guess is that HtmlUnit is failing to parse an external script. I would recommend either setting up a filter for that script (http://oinopa.com/akephalos/filters.html), or alternatively ignoring javascript errors (requires current master / the next release):

```
Capybara.register_driver :akpehalos do |app|
  Capybara::Driver::Akephalos.new(app, :validate_scripts => false)
end
```
