### ISSUE TITLE
Access HtmlUnit Cookies

### ISSUE THREAD

**Issue by bernerdschaefer** [bernerdschaefer/akephalos#4]
You should be able to read and remove cookies programatically. Capybara doesn't define an API for this, so it will have to be available some other way.

(requested by bjeanes)

**Comment by bjeanes** [comment]
RackTest and Selenium both have rudimentary ways to do this, ugly as they may be.

In Selenium you can get to the cookies with `Capybara.current_session.driver.browser.manage.all_cookies`. And in RackTest the (very un-elegant) way of doing it is `Capybara.current_session.driver.current_session.instance_variable_get(:@rack_mock_session).cookie_jar.instance_variable_get(:@cookies)`

Both drivers also expose ways to delete and set individual cookies, as well as clearing all cookies.

**Comment by bernerdschaefer** [comment]
I've added an API for interacting with cookies on master (84ea1f838). You can access them directly from the driver:

```
cookies = session.driver.cookies
cookies.each { |cookie| puts cookie.value }
cookies["user_id"].value # => "1"
cookies.remove(cookies["user_id"])
cookies.size # => 0
```

I'm not sure how I feel about being able to change / set cookies... I'd be open to hearing arguments for that, though.

**Comment by bjeanes** [comment]
Does it expose other parts of the cookie besides value, such as expiry, domain, and path?

I agree that adding this API is contentious as it is VERY open to abuse and in the wrong hands encourages improper integration testing. This plays closely to recent articles such as [Your Cuking It Wrong](http://elabs.se/blog/15-you-re-cuking-it-wrong) and I agree strongly.

However, there IS a case for exposing this API but heavily warning against using it to test values directly. My use case is emulating a quitting browser and testing the behaviour of returning visitors to a site. Specifically, in Cucumber, I might want to test "Given the user has never visited the site before" and behind the scenes clear all cookies, or test "Given I restart my browser" and just clear cookies that have an expiry in the past or no expiry at all (as a browser would).

There could be a better API to provide this functionality without accessing the cookies directly, but I argue that there may be other edge cases like this where accessing the cookies is actually necessary.

**Comment by bernerdschaefer** [comment]
You should be able to do all of that. The full cookie is exposed (name, value, domain, path, expiration, security), and you can remove individual cookies or remove all cookies. What's not exposed is _altering_ cookies or adding new cookies -- and I think it will probably remain that way.

**Comment by bjeanes** [comment]
I think that is a VERY reasonable compromise. I'd question the sanity of anyone setting cookie values in integration tests, too.

Thanks for this addition! When do you think you'll push a new gem version out?

**Comment by ssoroka** [comment]
Hmm..  If I want to write a regression test for a case that only happens when the user has a specific cookie set, I should be able to.  Best practices and capabilities are different things.
