### ISSUE TITLE
save_and_open_page Coding error

### ISSUE THREAD

**Issue by Nerian** [bernerdschaefer/akephalos#41]
I get this error:

Failure/Error: save_and_open_page
     "\xE2" from ASCII-8BIT to UTF-8

Any time I use capybara's save_and_open_page

Using ruby 1.9.2 and Capybara 0.4.0. I used one of the forks that introduce compatibility with Capybara 0.4.0.

https://github.com/sorentwo/akephalos

**Comment by Nerian** [comment]
I solved this by setting JRuby to use UTF mode. I sent  pull request.
In the mean time, any body can use:

```
gem 'akephalos', :git => "git@github.com:Nerian/akephalos.git"
```

**Comment by jeanbza** [comment]
That url should be https://github.com/Nerian/akephalos.git for the public.
