### ISSUE TITLE
Installing via Bundler is broken

### ISSUE THREAD

**Issue by jarrett** [bernerdschaefer/akephalos#47]
When installing via Bundler using `gem akephalos`, I get this error:

```
`open_uri_or_path': bad response Not Found 404 (http://production.cf.rubygems.org/quick/Marshal.4.8/akephalos-0.2.1-java.gemspec.rz) (Gem::RemoteFetcher::FetchError)
```

Install with `gem install` works. It also works to use:

```
gem 'akephalos', :git => "git@github.com:Nerian/akephalos.git"
```

While I realize it's not unusual for gems to be installed this way, I think it's better in general to make the rubygems.org distribution work. It's consistent with the way most gems are handled, it's more convenient, and it results in a cleaner installation.

**Comment by Nerian** [comment]
I plan to support my fork while Bernerd is missing in combat. So it is safe to use that repo, as I will be updating it with all the commits that I see in Akephalos's network. Feel free to send me any pull request.

**Comment by bernerdschaefer** [comment]
It appears that the 0.2.1-java release is missing on rubygems.org. I've reached out to @qrush to try and resolve this, but as an FYI, Nerian and other's fixes have been merged into master. Thanks.

**Comment by bernerdschaefer** [comment]
Okay. 0.2.1-java has been removed from rubygems, so this should no longer be an issue.
