### ISSUE TITLE
Add Integration Test for Subdomains

### ISSUE THREAD

**Issue by bernerdschaefer** [bernerdschaefer/akephalos#5]
There should be an integration test for being able to swap out the app_host between different subdomains. Here's a sample use case:

"What I would like to do is for example in an integration test do some action, set the subdomain and navigate around that subdomain, verify things look right, then set a new subdomain and verify my action doesn't show up there"

(requested by iamnader)

**Comment by iamnader** [comment]
Hi Bernard.  So I've looked into this a little bit.  I added a basic spec to my fork of akephalos: http://github.com/iamnader/akephalos/commit/80dad8ac49f723fc891c1fd2dc81aeac4ac71a89 and the spec passes!  That's the good news.

The bad news is when I run the exact same pattern from my integration test from my app, it's failing.  Here's a gist: http://gist.github.com/581146

Any idea what's going on?

**Comment by iamnader** [comment]
I should mention I'm using the latest versions of capy and akephalos from rubygems: 
   gem "capybara"
   gem "akephalos"

**Comment by bernerdschaefer** [comment]
I've added an integration test for this to master, and it passes as expected.

Looking at it, are you sure that test is running with akephalos? Just setting Capybara.javascript_driver won't make it use akephalos. You probably need:

```
def setup; Capybara.current_driver = :akephalos; end
def teardown; Capybara.use_default_driver; end
```

**Comment by iamnader** [comment]
I'll try that ASAP.  But I guess I'm confused. http://github.com/bernerdschaefer/akephalos says to set the javascript_driver.  When do you set the current_driver and when the javascript_driver?

**Comment by bernerdschaefer** [comment]
Yeah.. I'll update the text for that. In particular, that will work for out of the box only for cucumber, where capybara installs a before/after hook for setting current_driver automatically.

It is still the correct way / place to set that option, though, since it allows you to abstract away which driver you want to use, with, say, this for test/unit:

```
module JavascriptTest
  def setup
    super
    Capybara.current_driver = Capybara.javascript_driver
  end

  def teardown
    super
    Capybara.use_default_driver
  end
end

class SubdomainTest # ...
  include JavascriptTest
end
```

Or, with rspec2, something like:

```
RSpec.configuration.before(:all, :javascript => true) do
  Capybara.current_driver = Capybara.javascript_driver
end

RSpec.configuration.after(:all, :javascript => true) do
  Capybara.use_default_driver
end

describe "subdomains", :javascript => true do
  # ...
end
```

**Comment by iamnader** [comment]
Excellent that worked.  Somewhat tangential.  I'm trying to get my tests to run as quickly as possible.  Do you know if akephalos can run without starting a server a la envjs?
