### ISSUE TITLE
HtmlUnit & SVG graphics

### ISSUE THREAD

**Issue by pboling** [bernerdschaefer/akephalos#51]
In my app all the headless browser drivers, including akephalos, crash irrecoverably when loading jqplot.  I believe this is due to HtmlUnit crashing when loading javascript libraries that use svg graphics.  Would it be possible to catch/ignore jqplot or libraries that are problematic for HtmlUnit?

I would prefer to be able to test 'something' even if not all the javascript on my site is loaded.  It would be better than the 'nothing' I have now.

**Comment by bernerdschaefer** [comment]
I would take a look at using Akephalos' filters: http://oinopa.com/akephalos/filters.html

I've used them for filtering RaphaelJS, which has the same issue.
