### ISSUE TITLE
Is this the preferred repo

### ISSUE THREAD

**Issue by rurounijones** [bernerdschaefer/akephalos#52]
I was reading the following article which is pretty positive on akephalos

http://robots.thoughtbot.com/post/1658763359/thoughtbot-and-the-holy-grail

at the end of it they recommend using the thoughtbot branch "until the changes are pulled in". Is this still the case? From the network diagram it looks like there are some unpulled changes but I do not know if they are the ones in question. 

Any advice would be much appreciated.

**Comment by bernerdschaefer** [comment]
I would recommend using my repository now -- it's been updated to work with the latest version of capybara, and I've pulled in the most important changes from thoughtbot and others.

Cheers

**Comment by rurounijones** [comment]
Thank you for the update.
