### ISSUE TITLE
Javascript not triggering on change in a select box.

### ISSUE THREAD

**Issue by rurounijones** [bernerdschaefer/akephalos#56]
I have the following jQuery JavaScript:
    function set_unit_count() {
    the_count = 0
    if ($('#application_form_condition_set_attributes_admin').val() == "0") {
        the_count = $('.items input:checked').length;
    }
    if ($('#application_form_condition_set_attributes_admin').val() >= "1") {
        the_count = $('.items input:checked').length + 1;
    }
    $('.unit_line').each(function(index) {
        if (index < (the_count)) {
            $(this).find(":input").removeAttr("disabled");
        }
        else {
            $(this).find(":input").attr("disabled", "true").val('');
        }
    }); 

```
$('#application_form_condition_set_attributes_admin').change(function() { set_unit_count() });
$('.items input').change(function() { set_unit_count() });   
```

If the admin dropdown value is 0, enable the same number of unit_line inputs as there are .items checkboxes checked.

If the admin dropdown value is 1 or greater, enable the same number of unit_line inputs as there are .items checkboxes checked with an extra set enabled.

If the admin dropdown value is empty then by default all the .unit_line inputs are disabled.

This is triggered whenever a checkbox changes or the admin select_box changes.

I have tested this manually in various browsers without problem.

And I am using cucumber and capybara with akephalos set as the default javascript driver have have the following in my scenario
    Scenario: Selecting admin should make one unit set editable
    When I check "data"  
    And I select "0" from "application_form_condition_set_attributes_admin"
    And show me the page
    Then there should be "1" unit set editable

The "Then there should be "1" unit set editable" step fails. It looks like the JavaScript is not being executed as none of the  .input_line inputs are modified. 

However when I look at the page (Using the "And show me the page") I can see that the select box has the correct value and I can then change the dropdown value and trigger the JavaScript manually.

So it just looks like the JavaScript is not firing on the change.  Is there a known issue with firing JavaScript events on the changing of a select box?

Capybara 0.4.1.1
Akephalos 0.2.5

Any help or suggestions would be much apprciated. I am not a JavaScript guru but pretty sure I haven't messed it up.

**Comment by donaldpiret** [comment]
+1 for this, having the same issue

**Comment by rurounijones** [comment]
Have done another search around and I think this may be the same issue as #33

**Comment by rurounijones** [comment]
I have just upgraded to from Rails 3.0.3 to Rails 3.0.5 with the new jquery rails.js and it appears to fix this problem. Could someone else verify?
