### ISSUE TITLE
Decide how to handle server errors

### ISSUE THREAD

**Issue by bernerdschaefer** [bernerdschaefer/akephalos#7]
HtmlUnit by default raises an error when the remote server returns an exceptional status code.

This is generally acceptable for the case of a 500 error (unless you intend to _test_ the behavior of your 500 pages), but causes problems for other status codes, such as 422, which is returned by rails when a validation error occurs with respond_to :json and respond_with object.

**Comment by thedelchop** [comment]
Yes I am also experiencing this problem, I would like to filter for a redirect but it throws an exception instead of doing the redirect.

**Comment by whatbird** [comment]
yea, this is a show stopper. 422 is tossed all over the rails world. for better or worse.

adding "client.throwExceptionOnFailingStatusCode = false" in Akephalos::Client#initialize will do it

**Comment by bernerdschaefer** [comment]
Exceptions are no longer raised for failing status codes in master, and that will go out soon with the next release!
