### ISSUE TITLE
POST variables end up as GET variables

### ISSUE THREAD

**Issue by patrickhno** [bernerdschaefer/akephalos#72]
I have this HTML:

```
<form action'rollout_edit.php?sign=$sign' id='editform' method='POST'>
                < .... input fields .... >
                <input type='submit' value='Lagre endringer'>
</form>
```

And click the link with 'click_link'

And the apache log shows:

127.0.0.1 - - [21/Jun/2011:19:23:31 +0200] "GET /rollout/rollout_edit.php?mode=SAVE&name=TESTNAME&adr=TESTADR&pno=0870&city=Oslo&municipality=Oslo&max_speed      =512&comm=Cucumber+test&tk_sign=&length_to_tk= HTTP/1.1" 200 598

And sign is neither in the POST or GET variables.

(All the variables in the apache log are input fields.)

**Comment by Nerian** [comment]
There is not an equal '=' sign after the action method.

This should work:

```
<form action='rollout_edit.php?sign=$sign' id='editform' method='POST'>
            < .... input fields .... >
            <input type='submit' value='Lagre endringer'>
</form>
```

**Comment by patrickhno** [comment]
That is quite correct!
Firefox/selenium somehow figure it out anyways.
